application:
  - name: root-app-team-fe
    namespace: argocd
    source:
      repoURL: https://github.com/hamidaria70/gitops-team-fe.git
      path: argo-app
      targetRevision: HEAD
    destination:
      server: https://kubernetes.default.svc
      namespace: team-fe
